services:

  backend:
    image: sahildocker9082/chat-backend:latest

    restart: unless-stopped

    env_file:
      - /home/ubuntu/.env

    expose:
      - "1111"

  nginx:
    image: nginx:1.27-alpine

    restart: unless-stopped

    depends_on:
      - backend

    ports:
      - "80:80"

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro